### ISSUE TITLE
Widget Dissapears after Subscribing

### ISSUE THREAD

**Issue by suture** [jameslafferty/MailChimp-Widget#24]
It seems that the subscribe widget is no longer visible on the page after a user subscribes to the mailing list. I'm guessing that this is an intentional behavior? 

Is there a way to keep it visible?

**Comment by jameslafferty** [comment]
Disable cookies. :) I know this is a really, really old issue, but the behavior will be optional on a per-widget basis (defaulting to what you currently see) for the next release.
