### ISSUE TITLE
hardcoded wp-content in ns_widget

### ISSUE THREAD

**Issue by johnReeve** [jameslafferty/MailChimp-Widget#25]
Thanks for the plugin-- we've used it a number of times.

One issue that I notice din deploying it recent is that there are hardcoded references to wp-content directory in ns_widget_mailchimp.class.php; this is a bad practice as wp allows for custom content and plugin directories to be defined in WP_PLUGIN_URL and WP_CONTENT_URL .  You might want to change those two lines.

**Comment by jameslafferty** [comment]
Thanks! I don't think this is an issue in the rewrite, but I'll go over the code again with that in mind before releasing it.
