### ISSUE TITLE
widget just disappeared

### ISSUE THREAD

**Issue by alloyd1** [jameslafferty/MailChimp-Widget#27]
Hi my website is simplyrealmoms.com. the first widget on the sidebar is the fantastic mailchimp widget, but it suddenly disappeared. Since I don't know what happened to it, I'm not sure how to fix it. I attached a working and current non-working image here.

Any help would be greatly appreciated.

Thanks,

Allison

![Screen shot 2012-12-20 at 8 48 17 PM](https://f.cloud.github.com/assets/3094373/26099/89abbaee-4b10-11e2-8d18-f4b516ffe8ff.png)
![Screen shot 2012-12-20 at 8 48 06 PM](https://f.cloud.github.com/assets/3094373/26100/89b5c2b4-4b10-11e2-9c63-a4a91975d032.png)

**Comment by jameslafferty** [comment]
This behavior is intentional (once a user is signed up, you shouldn't bother them with a useless form). However, it'll be optional on a per-widget basis (defaulting to what you saw) in the next release.
